[tool.black]
line-length = 100
skip-magic-trailing-comma = true
target-version = ["py311"]

[tool.isort]
profile = "black"
force_single_line = true


[tool.mypy]
python_version = "3.11"
exclude = ["__init__.py", "src/tests"]

strict = true
warn_unused_configs = true
disallow_subclassing_any = false

show_error_codes = true
show_column_numbers = true

follow_imports = "skip"
ignore_missing_imports = true
no_site_packages = true
